name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the flask-app repo
        uses: actions/checkout@v3
      - name: authenticate to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: setup docker build
        uses: docker/setup-buildx@v1
        id: buildx
      - name: build flask app and push to dockerhub
        id: docker_build
        uses: docker/build-push-action@V2
        with:
          context: ./
          file: ./Dockerfile
          tags: rocahenr/gitops:latest
