name: CI
on: 
  #push: 
  #  branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile
